### PR TITLE
Add UKCP18 OpenDataset implementation and Notebook showing example usage

### PR DESCRIPTION
**Pull request by ciaransweet**
# What this PR is

This PR adds two files:

* `src/hazard/sources/ukcp18_rcp85.py` - An implementation of the `OpenDataset` protocol for fetching UKCP18 data for use in Hazard's indicator creation
* `notebooks/ukcp18_hazard_ DaysTasAboveIndicator.ipynb` - An example usage of the above implementation showing how to instantiate the class and to generate an indicator with it

## Breakdown of the UKCP18 `OpenDataset` implementation

At a high level, when `open_dataset_year` on the implementation is invoked by the model, the following steps occur:

* List all the files available for the given `gcm`, `scenario`, and `quantity`
* Parse their filenames and determine which file(s) contain data for the provided year
* Produce an `xarray.Dataset` from the matching file(s)
* Subset the dataset to only the year required
* Reproject the dataset to `EPSG:4326`
* Convert the `quantity` data's values to Kelvin from Celsius
* Return the data

# How you can test it

The best way is to play around with the notebook provided. It mimics the setup in `notebooks/launcher.ipynb`

### CODE REVIEW

**Comment by emileten** [comment]
Looks great @ciaransweet ! One limitation that I would note is that there is some documentation in this repository that has in it, hard-coded, references to the NASA data that's been used as a default historically. This markdown file for example : https://github.com/developmentseed/os-climate-hazard/blob/087360e4d80e57cd91c66b949fc6a6fe539b20f0/src/hazard/models/days_tas_above.md?plain=1#L10. 

I know that [this ends up in the inventory](https://github.com/developmentseed/os-climate-hazard/blob/087360e4d80e57cd91c66b949fc6a6fe539b20f0/src/hazard/models/days_tas_above.py#L93). Something to have in mind : if we create an inventory of our data we'll have a description of the model in it that says that it uses NASA-NEX as input which is wrong. We shouldn't worry about this for now I think, should just have it in mind.

**Review by emileten — APPROVED** [review]
LGTM, see my comment above!

**Comment by ciaransweet** [comment]
Good spot @emileten - Probably something we can template out eventually.

**Comment by emileten** [comment]
Another comment, sorry I realized now. 

Once we start using this 'in production' we should ask to someone more knowledgeable about the UKCP data on the client side (e.g. someone in a science team) how to handle this `member` parameter. For now we're using `member=1` by default. My intuition is that there are different members for different types of parameterization of the climate model.

**Comment by emileten** [comment]
Not sure I see the link, so in case, here is the issue https://github.com/sparkgeo/uk_eodatahub/issues/277#issuecomment-2238615920. Has a useful comment in it that provides context.

**Pull request merged**
